{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Name</th>\n",
       "      <th>Games Played</th>\n",
       "      <th>MIN</th>\n",
       "      <th>PTS</th>\n",
       "      <th>FGM</th>\n",
       "      <th>FGA</th>\n",
       "      <th>FG%</th>\n",
       "      <th>3PM</th>\n",
       "      <th>3PA</th>\n",
       "      <th>3P%</th>\n",
       "      <th>...</th>\n",
       "      <th>BLK</th>\n",
       "      <th>TOV</th>\n",
       "      <th>PF</th>\n",
       "      <th>EFF</th>\n",
       "      <th>AST/TOV</th>\n",
       "      <th>STL/TOV</th>\n",
       "      <th>Collage</th>\n",
       "      <th>Experience</th>\n",
       "      <th>Height</th>\n",
       "      <th>Pos</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>457</th>\n",
       "      <td>Toure' Murry</td>\n",
       "      <td>5</td>\n",
       "      <td>18</td>\n",
       "      <td>6</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>40.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>0.25</td>\n",
       "      <td>0.25</td>\n",
       "      <td>Wichita State University</td>\n",
       "      <td>1</td>\n",
       "      <td>192.5</td>\n",
       "      <td>SG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>378</th>\n",
       "      <td>Phil Pressey</td>\n",
       "      <td>50</td>\n",
       "      <td>600</td>\n",
       "      <td>177</td>\n",
       "      <td>64</td>\n",
       "      <td>174</td>\n",
       "      <td>36.8</td>\n",
       "      <td>16</td>\n",
       "      <td>65</td>\n",
       "      <td>24.6</td>\n",
       "      <td>...</td>\n",
       "      <td>6</td>\n",
       "      <td>41</td>\n",
       "      <td>54</td>\n",
       "      <td>243</td>\n",
       "      <td>2.85</td>\n",
       "      <td>0.73</td>\n",
       "      <td>University of Missouri</td>\n",
       "      <td>1</td>\n",
       "      <td>177.5</td>\n",
       "      <td>PG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>223</th>\n",
       "      <td>Jerome Jordan</td>\n",
       "      <td>44</td>\n",
       "      <td>383</td>\n",
       "      <td>138</td>\n",
       "      <td>50</td>\n",
       "      <td>94</td>\n",
       "      <td>53.2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>...</td>\n",
       "      <td>15</td>\n",
       "      <td>22</td>\n",
       "      <td>58</td>\n",
       "      <td>207</td>\n",
       "      <td>0.59</td>\n",
       "      <td>0.36</td>\n",
       "      <td>University of Tulsa</td>\n",
       "      <td>1</td>\n",
       "      <td>210.0</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>329</th>\n",
       "      <td>Matthew Dellavedova</td>\n",
       "      <td>67</td>\n",
       "      <td>1380</td>\n",
       "      <td>319</td>\n",
       "      <td>111</td>\n",
       "      <td>307</td>\n",
       "      <td>36.2</td>\n",
       "      <td>68</td>\n",
       "      <td>167</td>\n",
       "      <td>40.7</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>61</td>\n",
       "      <td>152</td>\n",
       "      <td>409</td>\n",
       "      <td>3.34</td>\n",
       "      <td>0.39</td>\n",
       "      <td>Saint Mary's College of California</td>\n",
       "      <td>1</td>\n",
       "      <td>190.0</td>\n",
       "      <td>SG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>Ben McLemore</td>\n",
       "      <td>82</td>\n",
       "      <td>2670</td>\n",
       "      <td>996</td>\n",
       "      <td>363</td>\n",
       "      <td>831</td>\n",
       "      <td>43.7</td>\n",
       "      <td>140</td>\n",
       "      <td>391</td>\n",
       "      <td>35.8</td>\n",
       "      <td>...</td>\n",
       "      <td>19</td>\n",
       "      <td>138</td>\n",
       "      <td>219</td>\n",
       "      <td>837</td>\n",
       "      <td>1.01</td>\n",
       "      <td>0.56</td>\n",
       "      <td>University of Kansas</td>\n",
       "      <td>1</td>\n",
       "      <td>192.5</td>\n",
       "      <td>SG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>249</th>\n",
       "      <td>Jordan Clarkson</td>\n",
       "      <td>59</td>\n",
       "      <td>1476</td>\n",
       "      <td>703</td>\n",
       "      <td>267</td>\n",
       "      <td>596</td>\n",
       "      <td>44.8</td>\n",
       "      <td>38</td>\n",
       "      <td>121</td>\n",
       "      <td>31.4</td>\n",
       "      <td>...</td>\n",
       "      <td>12</td>\n",
       "      <td>96</td>\n",
       "      <td>109</td>\n",
       "      <td>711</td>\n",
       "      <td>2.15</td>\n",
       "      <td>0.53</td>\n",
       "      <td>University of Missouri</td>\n",
       "      <td>R</td>\n",
       "      <td>192.5</td>\n",
       "      <td>PG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>297</th>\n",
       "      <td>Larry Drew II</td>\n",
       "      <td>12</td>\n",
       "      <td>219</td>\n",
       "      <td>46</td>\n",
       "      <td>20</td>\n",
       "      <td>58</td>\n",
       "      <td>34.5</td>\n",
       "      <td>4</td>\n",
       "      <td>26</td>\n",
       "      <td>15.4</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>25</td>\n",
       "      <td>13</td>\n",
       "      <td>48</td>\n",
       "      <td>1.80</td>\n",
       "      <td>0.24</td>\n",
       "      <td>University of California, Los Angeles</td>\n",
       "      <td>R</td>\n",
       "      <td>185.0</td>\n",
       "      <td>PG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>86</th>\n",
       "      <td>Cory Jefferson</td>\n",
       "      <td>50</td>\n",
       "      <td>531</td>\n",
       "      <td>183</td>\n",
       "      <td>75</td>\n",
       "      <td>167</td>\n",
       "      <td>44.9</td>\n",
       "      <td>2</td>\n",
       "      <td>15</td>\n",
       "      <td>13.3</td>\n",
       "      <td>...</td>\n",
       "      <td>21</td>\n",
       "      <td>20</td>\n",
       "      <td>61</td>\n",
       "      <td>240</td>\n",
       "      <td>0.80</td>\n",
       "      <td>0.50</td>\n",
       "      <td>Baylor University</td>\n",
       "      <td>R</td>\n",
       "      <td>202.5</td>\n",
       "      <td>PF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>232</th>\n",
       "      <td>Joe Harris</td>\n",
       "      <td>51</td>\n",
       "      <td>493</td>\n",
       "      <td>136</td>\n",
       "      <td>48</td>\n",
       "      <td>120</td>\n",
       "      <td>40.0</td>\n",
       "      <td>31</td>\n",
       "      <td>84</td>\n",
       "      <td>36.9</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>27</td>\n",
       "      <td>62</td>\n",
       "      <td>107</td>\n",
       "      <td>0.96</td>\n",
       "      <td>0.26</td>\n",
       "      <td>University of Virginia</td>\n",
       "      <td>R</td>\n",
       "      <td>195.0</td>\n",
       "      <td>SG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>486</th>\n",
       "      <td>Zach LaVine</td>\n",
       "      <td>77</td>\n",
       "      <td>1902</td>\n",
       "      <td>778</td>\n",
       "      <td>286</td>\n",
       "      <td>677</td>\n",
       "      <td>42.2</td>\n",
       "      <td>57</td>\n",
       "      <td>167</td>\n",
       "      <td>34.1</td>\n",
       "      <td>...</td>\n",
       "      <td>10</td>\n",
       "      <td>193</td>\n",
       "      <td>158</td>\n",
       "      <td>720</td>\n",
       "      <td>1.43</td>\n",
       "      <td>0.28</td>\n",
       "      <td>University of California, Los Angeles</td>\n",
       "      <td>R</td>\n",
       "      <td>192.5</td>\n",
       "      <td>PG</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>350 rows × 28 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                    Name  Games Played   MIN  PTS  FGM  FGA   FG%  3PM  3PA  \\\n",
       "457         Toure' Murry             5    18    6    2    5  40.0    0    0   \n",
       "378         Phil Pressey            50   600  177   64  174  36.8   16   65   \n",
       "223        Jerome Jordan            44   383  138   50   94  53.2    0    0   \n",
       "329  Matthew Dellavedova            67  1380  319  111  307  36.2   68  167   \n",
       "40          Ben McLemore            82  2670  996  363  831  43.7  140  391   \n",
       "..                   ...           ...   ...  ...  ...  ...   ...  ...  ...   \n",
       "249      Jordan Clarkson            59  1476  703  267  596  44.8   38  121   \n",
       "297        Larry Drew II            12   219   46   20   58  34.5    4   26   \n",
       "86        Cory Jefferson            50   531  183   75  167  44.9    2   15   \n",
       "232           Joe Harris            51   493  136   48  120  40.0   31   84   \n",
       "486          Zach LaVine            77  1902  778  286  677  42.2   57  167   \n",
       "\n",
       "      3P%  ...  BLK  TOV   PF  EFF  AST/TOV  STL/TOV  \\\n",
       "457   0.0  ...    0    4    2    2     0.25     0.25   \n",
       "378  24.6  ...    6   41   54  243     2.85     0.73   \n",
       "223   0.0  ...   15   22   58  207     0.59     0.36   \n",
       "329  40.7  ...    2   61  152  409     3.34     0.39   \n",
       "40   35.8  ...   19  138  219  837     1.01     0.56   \n",
       "..    ...  ...  ...  ...  ...  ...      ...      ...   \n",
       "249  31.4  ...   12   96  109  711     2.15     0.53   \n",
       "297  15.4  ...    0   25   13   48     1.80     0.24   \n",
       "86   13.3  ...   21   20   61  240     0.80     0.50   \n",
       "232  36.9  ...    2   27   62  107     0.96     0.26   \n",
       "486  34.1  ...   10  193  158  720     1.43     0.28   \n",
       "\n",
       "                                   Collage  Experience  Height  Pos  \n",
       "457               Wichita State University           1   192.5   SG  \n",
       "378                 University of Missouri           1   177.5   PG  \n",
       "223                    University of Tulsa           1   210.0    C  \n",
       "329     Saint Mary's College of California           1   190.0   SG  \n",
       "40                    University of Kansas           1   192.5   SG  \n",
       "..                                     ...         ...     ...  ...  \n",
       "249                 University of Missouri           R   192.5   PG  \n",
       "297  University of California, Los Angeles           R   185.0   PG  \n",
       "86                       Baylor University           R   202.5   PF  \n",
       "232                 University of Virginia           R   195.0   SG  \n",
       "486  University of California, Los Angeles           R   192.5   PG  \n",
       "\n",
       "[350 rows x 28 columns]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "def load_and_process(url_or_path_to_csv_file):\n",
    "\n",
    "    df = (pd.read_csv(url_or_path_to_csv_file)\n",
    "          .drop(columns = ['BMI','Weight','Team','Birth_Place','Birthdate','Age'])\n",
    "          .dropna()\n",
    "          .sort_values('Experience', ascending = True)\n",
    "         )\n",
    "    return df\n",
    "load_and_process('../../../data/raw/players_stats.csv')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
